SELECT
    PA_SCHED.SCHD_ID,
    PA_ENROLL_SEAT.ENRL_STAT_ID,
    PA_ENROLL_SEAT.STUD_ID,
    'GETLABEL:' || PA_ENROLL_STAT.ENRL_STAT_DESC || ':' || PA_ENROLL_STAT.ENRL_STAT_ID AS ENRL_STAT_DESC,
    PA_STUDENT.FNAME,
    PA_STUDENT.LNAME,
    PA_STUDENT.EMAIL_ADDR,
    'GETLABEL:' || PA_SCHED.SHORT_DESCRIPTION || ':' || "SHORT_DESCRIPTION" AS SCHD_DESC
FROM
    PA_SCHED
    LEFT JOIN PA_ENROLL_SEAT ON PA_SCHED.SCHD_ID = PA_ENROLL_SEAT.SCHD_ID
    LEFT JOIN PA_ENROLL_STAT ON PA_ENROLL_SEAT.ENRL_STAT_ID = PA_ENROLL_STAT.ENRL_STAT_ID
    LEFT JOIN PA_STUDENT ON PA_ENROLL_SEAT.STUD_ID = PA_STUDENT.STUD_ID
WHERE
    1 = 1
    AND PA_ENROLL_SEAT.STUD_ID IS NOT NULL
    /** and [security: PA_SCHED] */
    /** and PA_SCHED.SCHD_ID in [ScheduleSearch] */