SELECT
    PA_RQST.STUD_ID,
    PA_STUDENT.FNAME,
    PA_STUDENT.LNAME,
    PA_STUDENT.EMAIL_ADDR,
    BASIS.CPNT_ID,
    BASIS.CPNT_TYP_ID,
    BASIS.REV_DTE,
    BASIS.CPNT_ID || '_' || BASIS.CPNT_TYP_ID || '_' || BASIS.REV_DTE AS ITEM_KEY,
    PA_RQST.ENRL_STAT_ID,
    'GETLABEL:' || PA_RQST.ENRL_STAT_DESC || ':ENRL_STAT_ID' AS ENRL_STAT_DESC
FROM
    (
        SELECT
            DISTINCT PA_SCHED.ACT_CPNT_ID AS CPNT_ID,
            PA_SCHED.CPNT_TYP_ID,
            PA_SCHED.REV_DTE
        FROM
            PA_SCHED
        WHERE
            1 = 1
            /** and PA_SCHED.SCHD_ID in [ScheduleSearch] */
    ) BASIS
    LEFT JOIN PA_RQST ON BASIS.CPNT_ID = PA_RQST.CPNT_ID
    AND BASIS.CPNT_TYP_ID = PA_RQST.CPNT_TYP_ID
    AND BASIS.REV_DTE = PA_RQST.REV_DTE
    LEFT JOIN PA_STUDENT ON PA_RQST.STUD_ID = PA_STUDENT.STUD_ID
WHERE
    PA_RQST.STUD_ID IS NOT NULL