SELECT
    PA_SCHED.SCHD_ID,
    PS_SCHD_RESOURCES.START_DTE as CLASS_START_DATE,
    PS_SCHD_RESOURCES.END_DTE as CLASS_END_DATE,
    PA_CPNT.CPNT_TITLE,
    PA_CPNT.CPNT_DESC,
    PA_CPNT.CPNT_ID,
    PA_CPNT.CPNT_TYP_ID,
    PA_CPNT.REV_DTE,
    PA_CPNT_TYPE.CPNT_TYP_DESC,
    PA_CPNT.CPNT_ID || '_' || PA_CPNT.CPNT_TYP_ID || '_' || PA_CPNT.REV_DTE AS ITEM_KEY
FROM
    PA_SCHED
    LEFT JOIN PS_SCHD_RESOURCES on PS_SCHD_RESOURCES.SCHD_ID = PA_SCHED.SCHD_ID
    LEFT JOIN PA_CPNT on PA_CPNT.CPNT_ID = PA_SCHED.ACT_CPNT_ID
    AND PA_CPNT.CPNT_TYP_ID = PA_SCHED.CPNT_TYP_ID
    AND PA_CPNT.REV_DTE = PA_SCHED.REV_DTE
    LEFT JOIN PA_CPNT_TYPE on PA_CPNT_TYPE.CPNT_TYP_ID = PA_CPNT.CPNT_TYP_ID
WHERE
    1 = 1
    /** and [security: PA_SCHED] */
    /** and PA_SCHD.SCHD_ID in [ScheduleSearch] */