SELECT
    'SCHED' AS COL_TYPE,
    PA_USRCL_SCHED.COL_NUM,
    PA_USRCL_SCHED.LABEL,
    PA_USRCL_SCHED.REFERENCED,
    PA_USRRF_SCHED.USER_ID,
    PA_USRRF_SCHED.USER_DESC
FROM
    PA_USRCL_SCHED
    LEFT JOIN PA_USRRF_SCHED ON PA_USRCL_SCHED.COL_NUM = PA_USRRF_SCHED.COL_NUM
WHERE
    EXISTS (
        SELECT
            1
        FROM
            PA_I18N_LOCALIZED_LABEL
        WHERE
            PA_I18N_LOCALIZED_LABEL.LABEL_ID = PA_USRCL_SCHED.LABEL
            AND PA_I18N_LOCALIZED_LABEL.LABEL_VALUE NOT LIKE 'label.%'
    )
UNION
SELECT
    'USER' AS COL_TYPE,
    PA_USRCL_STUD.COL_NUM,
    PA_USRCL_STUD.LABEL,
    PA_USRCL_STUD.REFERENCED,
    PA_USRRF_STUD.USER_ID,
    PA_USRRF_STUD.USER_DESC
FROM
    PA_USRCL_STUD
    LEFT JOIN PA_USRRF_STUD ON PA_USRCL_STUD.COL_NUM = PA_USRRF_STUD.COL_NUM
WHERE
    PA_USRCL_STUD.COL_NUM NOT IN ('1100', '1129', '1130')
    AND EXISTS (
        SELECT
            1
        FROM
            PA_I18N_LOCALIZED_LABEL
        WHERE
            PA_I18N_LOCALIZED_LABEL.LABEL_ID = PA_USRCL_STUD.LABEL
            AND PA_I18N_LOCALIZED_LABEL.LABEL_VALUE NOT LIKE 'label.%'
    )
ORDER BY
    COL_TYPE,
    COL_NUM